### ISSUE TITLE
TimePicker widget

### ISSUE THREAD

**Issue by rishson** [dojo/widgets#100]
# Specification
This widget provides time picker behaviour.
 
<img width="102" alt="screen shot 2017-04-06 at 2 33 56 pm" src="https://cloud.githubusercontent.com/assets/468596/24757614/a30e092e-1ad7-11e7-95c4-44f71024f52b.png">

## Features
- can support AM/PM labels
- can support 12 and 24hr times
- can be passed a value that sets the currently displayed time

## Features excluded from this version
- timezone support, e.g. optional picker after the time [16:20][PM]**[BST]**
- default to current time if no time passed in
- falls back to native mobile UI on mobile

**Value-add of the widget (e.g. why use rather than just use VDom directly)**
Ability yo choose times

**List of callback funcs that can be passed in props (if any)**
`onHide`
`onShow`

**Mouse/keyboard interactions (if any)**
Ability to scroll through the times when choosing, using mouse and keyboard.

**Mandatory/valid/empty/wait states (if any)**
Mandatory
Disabled
Enabled

**Is the widget controlled/uncontrolled**
Controlled

**List of any icons needed**
Clock icon for input addon (used to launch the time picker)

**Design input required (inc responsive design)**
Look and feel of the widget.

**Any other considerations**:

## Questions
What format should be used to get/set the time data?

## Acceptance criteria
When I click the 'clock' icon on the input, the timepicker should be shown in a direction that makes best use of screen real estate, e.g. if the input is at the bottom of the screen, then the timepicker should be shown above the input
When I set and invalid time, e.g. `25:10`, then the input will show as `invalid`.

**Comment by tomdye** [comment]
Does it only fall back to native on mobile, or wherever native is available?

**Comment by mwistrand** [comment]
@tomdye It sounds like using native as a fallback is not included in the initial round. But when it is implemented, I'd recommend a `useNative` property so the developer can control when the native `<input>` is displayed and when the custom implementation is used.

@rishson According to [the spec](https://www.w3.org/TR/html5/forms.html#time-state-(type=time)), the `<input>` itself requires a formatted [time string](https://www.w3.org/TR/html5/infrastructure.html#valid-time-string), so we should allow at least that to be passed in for the `value`, `min`, and `max` properties. I also like the idea of allowing a `Date` object to be passed in, as well as a `{ hour: number; minute?: number; second?: number; }` object to avoid any ambiguity inherit in the `Date` object.

**Comment by matt-gadd** [comment]
I know in @smhigley's select PR she has a `useNativeSelect` property, so perhaps it might be worth standardising a property across widgets to control native use?

**Comment by rishson** [comment]
BTW, specs are discussions until we have consensus, do don't treat as carved in stone.

**Comment by smhigley** [comment]
I like the idea of a standardized `useNative` property, although it's worth mentioning that in Select the implementation has resulted in two mostly-separate widgets in one. Not sure if we want to make that a common pattern.

Select is a little special in that the native implementation is markedly better on mobile devices and not really reproducible. Time pickers also have a decent separate mobile implementation, but since you can also type directly into the field, I'm not sure how much preserving the native UI matters.

**Comment by mwistrand** [comment]
I'm going mostly from the [spec](https://www.w3.org/TR/html5/forms.html#time-state-(type=time)), but how does the following API sound?

```typescript
interface TimeOptions {
  hour: number;
  minute?: number;
  second?: number;
}

interface TimePickerProperties {
  disabled?: boolean; // defaults to false
  invalid?: boolean; // defaults to false
  start?: string | TimeOptions;
  end?: string | TimeOptions;
  readOnly?: boolean;  // defaults to false
  required?: boolean; // defaults to false
  step?: number; // defaults to 60
  value?: string | TimeOptions;
  formatOption?: (option: TimeOptions) => string;
  onChange?: (value: TimeOptions) => void;
  onBlur?: (value: TimeOptions) => void;
  onFocus?: (value: TimeOptions) => void;
  onValidate?: (valid?: boolean) => void;
}
```

**Notes**:

- `start` and `end` correspond to the `min` and `max` properties, respectively, but since the range can be [discontinuous](https://www.w3.org/TR/html5/forms.html#has-a-periodic-domain), `start` and `end` seem more natural.
- `formatOption` allows the application to determine how individual options are displayed in the options list to the user. Since `input[value]` must still be a [valid time string](https://www.w3.org/TR/html5/infrastructure.html#valid-time-string), this is a display-only property.
- The input value is validated in response to the `onblur` and `onchange` events. The value is considered to be valid if it is at least the specified minimum (`start`) and at most the specified maximum (`end`). A boolean `valid` flag is passed to an optional `onValidate` property method that can determine how the application responds to valid/invalid values.

**Questions**

- Since the options list will be managed internally, is there a need for `onHide` and `onShow` properties?
- The API suggested above passes an object instead of a [time string](https://www.w3.org/TR/html5/infrastructure.html#valid-time-string) to property methods. This is mostly to avoid the need for additional parsing, but would it be better to just use a time string? Also, I prefer the use of singular unit names within the `TimeOptions` interface, but if anyone thinks plural names would be better, please say so.

**Example**

```typescript
w(TimePicker, {
  start: { hour: 22 }, // 22:00
  end: { hour: 1, minute: 23, second: 45 }, // 01:23:45
  step: 1, // one second
  invalid: !this.state.valid,
  onValidate: (valid) => {
    this.setState({ valid });
  },
  formatOption: (option) {
    const { hour, minute, second } = option;
    const date = new Date();
    date.setHours(hour);
    date.setMinutes(minute);
    date.setSeconds(second);
    // import { formatDate } from '@dojo/i18n/date';
    return formatDate(date, { time: 'short' });
  }
});
```

**Comment by dylans** [comment]
I see that timezone support is excluded from the widget which is ok for now. That said, as soon as someone wants to use this for its most common use case (schedule an appointment), we're going to need to support timezone (at least for the internal datetime format). So we should probably add a follow-up issue for that soon, @rishson.

**Comment by rishson** [comment]
Related: Can I get votes on having a `useNativeElement` convention across widgets that want to offer native elements on mobile?
I'd prefer a standard property name across all widgets (to reduce API learning time).

**Comment by tomdye** [comment]
I think it should revert to native by default on mobile devices.

**Comment by rishson** [comment]
@tomdye this was discussed previously and it was decided that an application would be better sniffing the env once and passing `useNativeElement` into each stateless widget, rather than adding env sniffing to all widgets.

**Comment by tomdye** [comment]
That is what I was eluding to @rishson

**Comment by smhigley** [comment]
I like a standardized `useNativeElement` convention for widgets that need it, although I think we should be selective about which ones do. Select definitely did, and I see the case for Timepicker, but I don't really like the idea of building lots of dual custom/native widgets with parallel functionality.

**Comment by rishson** [comment]
@smhigley agree.
I'll add a question to the spec: 'Is native element support required?'.
I'll also open a discussion issue about parallel functionality.

**Comment by smhigley** [comment]
Also, @mwistrand don't forget `label` in the API. Take a look at any of the other form widgets for how it's used :)

**Comment by devpaul** [comment]
I see the benefits in using a boolean because it’s simple, but in general it’s better to avoid using booleans as parameters to split code paths internally and instead explicitly define separate classes (or functions) for each code path.

Selecting between different presentations is a very common problem for applications that support both desktop and mobile presentations. In desktop things like drop-downs are generally OK, while a mobile device user would prefer to have a full screen modal presentation of the controls.

Rather than switching on a boolean and using native controls, I would like us to have a general solution for selecting control presentation and leverage that for providing native controls.

**Comment by mwistrand** [comment]
@devpaul That is a very reasonable question, and for the most part we have avoided injecting too much responsiveness directly into the widgets, favoring the use of an application-specific control for determining which widget is used, rather than how a single widget is rendered.

In the particular instance, I believe a wrapper around the native `<input type="time">` would be light enough that the convenience provided by a simple `useNativeElement` property outweighs the benefits of creating an entirely different widget for it.

**Comment by bitpshr** [comment]
@mwistrand Looking at the API, should the component handle validation at all? All other components so far rely purely on an `invalid` property that's passed from the parent, and it's the parent's responsibility to determine validity. The TextInput doesn't determine if its value is valid based on a `pattern` property, for example; this (and other properties) were intentionally omitted in favor of parent validation.

**Comment by smhigley** [comment]
I agree with @bitpshr on validation, although I think it still needs `start` and `end` for the input's `min` and `max` attributes.

**Comment by mwistrand** [comment]
The `start` and `end` properties would also be needed to populate the menu, correct? `ComboBox` delegates this to the parent, but that seems odd for this widget.

**Comment by mwistrand** [comment]
I don't know why this didn't occur to me earlier, but `ComboBox` can be used directly for the custom input. There's still some cleanup to do, but the POC can be found [here](https://github.com/mwistrand/widgets/blob/100-timepicker-native/src/timepicker/TimePicker.ts).
