### ISSUE TITLE
Breadcrumb Widget

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#1124]
Please put design / thoughts on this ticket.
We should create a breadcrumb widget drawing inspiration from:

- https://material-ui.com/components/breadcrumbs/
- https://ant.design/components/breadcrumb/

We should keep this as simple as possible and not get tied up on routing etc.

**Comment by mwistrand** [comment]
The simplest implementation is to provide a single widget with a few configuration props that renders its children to an ordered list within a `<nav>`:

```
<Breadcrumb separator="/" aria-label={messages.breadcrumb}>
  <Link to={outlets.root}>{messages.home}</Link>
  <Link to={outlets.widgets}>{messages.widgets}</Link>
  <Link
    aria-current="page"
    to={outlets.widgets.breadcrumb}
  >
    {messages.breadcrumb}
  </Link>
</Breadcrumb>
```

The downside is the documentation would need to make clear that the current page link needs to include an `aria-current="page|step"` attribute and the root `<Breadcrumb>` needs either an `aria-label` or `aria-labelledby` attribute. However, it should still be simple to add additional features like limiting the number of items displayed should it be decided in the future that such features are useful.

Alternatively, an `items` config property could be used instead of children (which is how [Ant](https://ant.design/components/breadcrumb/) manages its breadcrumbs). Doing so, however, would require a well thought-out design to allow the same flexibility that is provided by using `children`, and even with a config it would likely not be possible to hide the accessibility concerns from the developer.

**Comment by tomdye** [comment]
I think that the second approach would work well for this following a similar pattern to the checkbox group widget. We can offer up an items property and handle the aria props etc for the user. We would simply render spans or hrefs ( if the user has specified a link address perhaps?). Further to this, we could offer a custom renderer via a child property which gets called for each of the `items`, thus giving the user the chance to render whatever they want. Further to this, we could later create a specific `RouterBreadcrumb` perhaps which uses it's own custom renderer to make `Outlet` widgets for each item. I think this approach gives us the most flexibility going forward and controls the addition of the appropriate aria tags etc.

**Comment by mwistrand** [comment]
@tomdye I've opened a [basic draft PR](https://github.com/dojo/widgets/pull/1155) to demonstrate the proposed API. Once the PR builds you should be able to view the examples.

```
interface BreadcrumbItem {
	href?: string;
	key: string;
	label: DNode;
	title?: string;
}

interface BreadcrumbProperties {
	current?: number;
	itemLevel?: 'page' | 'step';
	items: BreadcrumbItem[];
	label: string;
	separator?: DNode;
}
```

**Comment by tomdye** [comment]
@mwistrand I think that we can enhance this to support the custom renderer in a consistent way to our radio / checkbox group. In order to support that we would provide users with a single child renderer which they would use to render both the items and the separators.
To enable this we should split this into both `BreadCrumb` and `Crumb` (or similar). That way, when creating a custom layout / separator, the users can import and use the Crumb, as would the main widget itself.

ie.

```tsx
<BreadCrumb items={items}>
{(items) => {
   return items.map(item => <Crumb>{item.label}</Crumb>).join('>');
}}
</BreadCrumb>
```

Also, do you think the `current` prop is necessary? As with the custom renderer, i think we should assume the last item is the current and allow them to change it via a custom renderer should they so wish.

what do you think?

**Comment by mwistrand** [comment]
That might be ok. The benefit of using an item-level renderer instead of a list-level renderer is we get to decide for the user that an ordered list is the best way to render breadcrumbs and also make it easier to change the separator. If, however, we're not interested in those benefits/making those kinds of decisions for users, then we can remove the `separator` and `itemLevel` properties (just use "/" and "page" in the default renderer, respectively) and let users determine the correct markup in their own custom renderers.

As for `current`, removing that should fine. We could use the last item by default, and a custom renderer could change that as need be (for example, in a breadcrumb that displays steps in a wizard).

```
// for rendering `<Crumb>`, I'm assuming that providing optional href/title
// properties for links is still desirable, as otherwise it's unclear to me exactly
// what `<Crumb>` is intended to accomplish.
interface BreadcrumbItem {
  href?: string;
  label: string;
  title?: string;
}

interface CrumbProperties {
  current?: 'page' | 'step';
  item: BreadcrumbItem;
}

interface Breadcrumb {
  label: string;
  items: BreadcrumbItem[];
}
```

**Comment by tomdye** [comment]
@mwistrand whilst I appreciate your concern re. orderer lists, we've been moving other widgets over to child renderers instead of item renderers as a consistent pattern. This approach gives the user whatever flexibility they need to change separator / orientation / direction / appearance etc in which ever way they chose.

I also think that to further match up with `CheckboxGroup` / `RadioGroup` we should name these widgets `BreadcrumbGroup` and `Breadcrumb`.
