### ISSUE TITLE
Change TimePicker to use `Select` and convert to function based

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#1142]
Combobox is being deleted so timepicker should be updated to use the new approach with select and menu.

- convert to function based
- use icache
- accept initialValue
- use select
- remove combobox usage

**Comment by rorticus** [comment]
Looking around and current properties and aligning with what Select currently supports. Im thinking something like,

```tsx
export interface TimePickerProperties {
	/** Set the disabled property of the control */
	disabled?: boolean;

	/** Callback to determine if a particular time entry should be disabled */
	timeDisabled?: (time: string) => boolean;

	/** Adds a <label> element with the supplied text */
	label?: string;

	/** The name of the field */
	name?: string;

	/** The initial selected value */
	initialValue?: string;

	/** Called when the value changes */
	onValue?(value: string): void;

	/** Indicates the input is required to complete the form */
	required?: boolean;

	/** Callabck when valid state has changed */
	onValidate?(valid: boolean): void;

	/** The maximum time to display in the menu (defaults to '23:59:59') */
	max?: string;

	/** The minimum time to display in the menu (defaults to '00:00:00') */
	min?: string;

	/** The number of seconds between each option in the menu (defaults to 60) */
	step?: number;

	/** How the time is formatted. 24 hour, 12 hour, or locale-specific format (defaults to 24) */
	format?: '24' | '12' | 'locale';
}
```

## What's changed
- Updated properties to be in parity with modern widget patterns (not so many callbacks, managed values)
- Renamed `start` and `end` to `max` and `min` to bring inline with native time picker options.
- Added a `format` to allow for easy changing of common formats. In the future we could possibly make this also accept a callback so the user can format however they want.

## What we'll lose

There are a few examples that won't work any longer, so we'll delete those.

* **Filtered On Input** - No longer makes sense since there is nowhere to type.
* **Opens On Focus** - No longer makes sense since its a select box
*  **Native** - Will no longer be supported
