### ISSUE TITLE
Calendar: Make uncontrolled

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#1220]
The calendar is currently fully controlled.
We should make the calendar uncontrolled to line up with other widgets APIs.

The user should not have to set month / year / selectedDate or provide callbacks for onDateSelect / onMonthChange / onYearChange.

As per other widgets, the calendar should support `onValue` and `initialValue` properties.

**Comment by maier49** [comment]
Do we really want to remove the ability to specify a month and year without selecting a date. Would having initialMonth and initialYear properties as well as initialValue be overkill?

**Comment by maier49** [comment]
In addition to `onValue` and `initialValue`, the calendar will also support `initialYear`/`initialMonth` and `onMonth`/`onYear`. The purpose of these is to support use cases where a calendar should display an initial month/year but not have a date selected, and so that a user can monitor the calendar's navigation before a date is selected in case some other elements on the page should be synced to the calendar.
