### ISSUE TITLE
SlidePane theme not working

### ISSUE THREAD

**Issue by jellison** [dojo/widgets#1317]
#### Bug

SlidePane theme isn't working correctly. Likely due to a theme compose prefix without a composes in the dojo theme to re-apply the original styles as well as the changes.

### Actual

it's just empty box with no styling ;)
![image](https://user-images.githubusercontent.com/41762295/78373953-3f42a600-7599-11ea-9d81-ca7844e133d3.png)

### Expected

![image](https://user-images.githubusercontent.com/41762295/78373922-3520a780-7599-11ea-9152-3fdf5e6e12da.png)

**Comment by tomdye** [comment]
This issue is partly caused by `Parade` and also appears to be a problem in that the `material` theme for slide pane does not work at all.

We need to write a slide-pane material theme for this widget. This could be as simple as defining a width and adding the animation. We could also consider moving some of this out to fixed css as the slide animation is integral to the widget functionality itself.
