### ISSUE TITLE
Allow time picker to be controlled

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#1344]
## Proposal

As per issue #1330 we are adding in a controlled version of each of our `initial*` properties. These will allow the widget to be fully controlled should the user wish. 

## New Properties

- `value?: string`

**Comment by maier49** [comment]
How exactly do we want this to behave. The partially controlled approach actually works how I'd typically think of a controlled time picker. The text input can freely change and then the callback fires when a valid time is typed or selected. So for the fully controlled scenario in #1350 I made it so that the `onChange` will fire for any change, regardless of whether the value is valid, and the passed in value will always be what is shown. Meaning that the end user would need to plan for the fact that they may get invalid values.

If that's not correct then I'm not sure what behavior would be more controlled than the existing behavior but still desirable.

**Comment by tomdye** [comment]
@maier49 I believe this is the same issue that @rorticus came across when addressing the typeahead as he did not want to callback via `onValue` with partial / incorrect values. What he came up with is here: 
https://github.com/rorticus/widgets/blob/issue-1011/src/typeahead/index.tsx#L100-L113

Seems to work as expected and in a controlled manner. Would this approach work here too?
