### ISSUE TITLE
Wizard should actually be a Container too

### ISSUE THREAD

**Issue by matt-gadd** [dojo/widgets#1611]
*Enhancement** 
The current wizard behaviour is not very useful as it does not actually allow users to pass content, it should be more like our other containers. For example it's currently impossible to actually implement the material vertical stepper behaviour:

![image](https://user-images.githubusercontent.com/2183490/101358564-eeefb680-3892-11eb-939f-f64d60c8101c.png)

**Comment by bitpshr** [comment]
The current `Wizard` widget accepts a `steps` prop and optionally leans on a custom internal step renderer that's passed in as a child to the widget itself. For example, the following would be used to render a `Wizard` with a custom renderer for each step.

```ts
<Wizard steps={[ /* ... */ ]}>
    {{
        step: (status, index, step) => (
            <div>{status === 'complete' && '✅'} {step.title}</div>
        )
    }}
</Wizard>
```

From the perspective of a consumer, this setup is a little roundabout:

1. The `steps` prop does not allow arbitrary `content` in an obvious way (e.g. `description` or `subTitle` would have to be used currently.)
1. Using the default step renderer is probably more common than using a custom step renderer, yet the latter is taken as declarative `children`.

I think that the `Wizard` should be updated in the following ways:

1. `Step` should take an additional `content` property that can be used to pass arbitrary content in addition to the other elements (title, subtitle, description.)
1. `Wizard` should take its steps as children, and its custom step renderer should be a prop (rather than the other way around.)

This would make the most common use of the `Wizard` more expected in terms of required markup:

```ts
<Wizard>
    {[ /* step config */ ]}
</Wizard>
```

cc @matt-gadd @agubler @tomdye

**Comment by bitpshr** [comment]
Ok, two new options:

**Option 1**

```tsx
<Wizard>
	<Step status="pending">
		{{
			title: "Foo",
			subTitle: "Such foo",
			description: "This is foo",
			content: <SomeContentWidget />
		}}
	</Step>
	<Step status="pending">
		{{
			title: "Bar",
			subTitle: "Such bar",
			description: "This is bar",
			content: <SomeOtherContentWidget />
		}}
	</Step>
</Wizard>
```

**Option 2**

```tsx
<Wizard>
	<Step
		title="Foo"
		subTitle="Such foo"
		description="This is foo"
		status="pending"
	>
		<SomeContentWidget />
	</Step>
	<Step
		title="Bar"
		subTitle="Such bar"
		description="This is bar"
		status="pending"
	>
		<SomeOtherContentWidget />
	</Step>
</Wizard>
```


I prefer option 2 since it provides a (subjectively) nicer API that is also more restrictive. If a consumer passes arbitrary content for `title`, it may look weird since we apply specific internal styles to this render result. I feel like restricting `title`, `subTitle`, and `description` to be strings, while still allowing arbitrary content of need be, maintains internal theming while still being flexible enough.
