### ISSUE TITLE
Event listeners

### ISSUE THREAD

**Issue by matt-gadd** [dojo/widgets#182]
The current widget system supports adding arbitrary event listeners to the outer node of widgets from the parent. This seems like a leak in encapsulation - me as a widget author should decide what event listeners I want to support. As well as this there are the following limitations to the current system using `w`:

* Unable to attach to anything other than the outer node of the widget
* Unable to support custom callbacks or handlers

We can potentially solve this via the new property system https://github.com/dojo/widgets/pull/181. Consumers would prop pass function handlers (like we do today in the `listeners` object), in which a widget author would simply connect up to `v` inside their widget.

**Comment by agubler** [comment]
Initially I think the best approach would be to define a recommended best practice for creating and attaching event listeners within dojo2 widgets that can be used for both the top level node and any children nodes.

**Comment by agubler** [comment]
**Proposal** (as per pull request): Recommend that all event listeners/handlers supported by a widget are defined on the widget instance; these can either implement with some internal encapsulated widget functionality or delegate to a function handler that has been received by the widget via properties.

This could potentially be a little verbose and perhaps cumbersome but would be a consistent way to reference the listeners regardless of which node they need to be attached (top level or children). In the future we could absolutely (and should look to) add some syntactic sugar in order to reduce the tediousness for the widget authoring experience.
