### ISSUE TITLE
Nesting structure for widgets

### ISSUE THREAD

**Issue by rishson** [dojo/widgets#20]
We need to decide on if we will sub-divide our widgets.
3 possible options (please suggest others):

1) don't subdivide:
All widgets live in `dojo/widgets/src`. All are published as `@dojo/widgets/createSomeWidget`.

2) Use [atomic design](http://atomicdesign.bradfrost.com/chapter-2/) as out nesting structure:
Widgets live in `dojo/widgets/src/atoms`, `dojo/widgets/src/molecules` etc and are published as `@dojo/widgets/atoms/createTextBox` etc

3) Use previous dojo1 type divisions:
Widgets live in `dojo/widgets/src/form`, `dojo/widgets/src/layout` etc and are published as `@dojo/widgets/layout/createSlidePane` etc 

Of course, we can adhere to 1 repo convention but publish under another if we so desired.

**Comment by rishson** [comment]
Refs #13

**Comment by rishson** [comment]
I'm mostly concerned with the publish path - internally we can deal with whatevs. The idea is to have a focus on a stated design principle - @itorrey suggested atomic design. If we have lots of tutorials with this stated, then it makes sense to publish widgets under the same groupings. I dislike pretty much everyone else's attempts to group widgets, so am actually coming round to atomic design - just because its so generic and no-designery

**Comment by jjrv** [comment]
It sounds like all Dojo widgets would be (or should be) "atoms". Distinguishing more complex things like a calendar or dgrid as a totally different kind of animal compared to a textbox doesn't seem helpful to the users. From their point of view, all Dojo widgets are probably basic building blocks.

Design of a higher level hierarchy should be application-specific, or at least not dictated by simply using Dojo widgets.

When publishing on NPM, each `@dojo/something` is going to be a single package. I like option 3, as long as the packages are conveniently grouped. Maybe a fancy calendar, even if it was considered a form widget, should be in a different package than a simple button, to reduce bloat when just the button is needed.

Discoverability of the source code might be easier if the Github repos are organized similarly to the NPM packages.

**Comment by dylans** [comment]
> Discoverability of the source code might be easier if the Github repos are organized similarly to the NPM packages.

While I agree in theory, If every widget was a separate repo, the maintainability of the meta tasks alone for each release is going to get out of hand without some significant work to automate the tagging and publishing of releases (we probably need to do that anyway). Also I'm not sure how useful it really is to have each form field replacement be a separate repo, given that there's a lot of shared code across similar widgets.

For convenience, I guess simpler widgets that are likely to be used by most users should live in one repo, and more complex widgets get their own repo (e.g. dgrid, calendar, chart)... dgrids, calendars, and charts themselves are likely to exist in several different forms and those packages may be more than 1 widget, but are grouped logically by intent.

The primary reason for separate repos are:

* Comprehension, it's easier to quickly learn a particular repo and become an expert in that if they want to contribute to something smaller than all of Dojo 2
* Modularity/flexibility/dependency size (though as noted, we can decouple the npm usage of a single widget from the structure of the repo)
* Independent releases (e.g. a more actively developed widget can release more frequently).

To the last point, my expectation is that, for simplicity, all Dojo 2 packages will release at the same time for x.y releases, but each package may have varied numbers of x.y.z releases. This means we will probably end up at 3.0 a lot faster than 2.0. :)

Regarding Atomic design, their approach seems to be that atoms are small widgets, molecules and combined widgets, organisms use layout widgets with molecules inside them, templates are a way to describe the reuse of organisms, and pages are constructed by populating data into organisms? That said, I don't like the hierarchy of these are atoms, these are molecules, etc., as that reeks of skeuomorphism.

I think Atomic design gets some things right, but it definitely feels like it's trying to teach designers OO rather than functional approaches to organizing things, but maybe I'm wrong and the same patterns work in a world of composition? There must be a functional analog or tweaks to that approach that offers similar benefits?

Finally, the model of layout, form, etc. might actually be the same as Atomic design but with names that match purpose based on my assumptions above? If we go down that route, it might be better then to have something like this for core widgets:

* @dojo/widgets-form
* @dojo/widgets-layout
* @dojo/widgets-?

And then for larger widget projects perhaps drop the widget prefix (or perhaps for the above, drop the widgets- ?):

* @dojo/dgrid
* @dojo/charts (leveraging @dojo/widget-core and @dojo/dataviz)
* @dojo/gauges
* @dojo/visualizations
* @dojo/calendar
* @dojo/webvr (building on @dojo/widget-core and something like dataviz but for AFrame or React VR)?

Obviously not all of the above are part of a release any time soon, but I'm trying to think longer term to help decide how to organize things... for example, are there any widgets that might be offered in HTML, SVG, and WebVR formats?

**Comment by agubler** [comment]
Thanks for the comment @jjrv, from my perspective I think initially there should be two separate types of publishing for `dojo/widgets`.

The first for the complete package, with all the widgets where the repository folder structure will most likely be directly reflected by the widget imports. 

The second is publishing each widget individually to `npm` using a convention based on the widget name - something like `@dojo/widget-textinput` or `@dojo/textinput-widget` that a consumer can discretely install and use without the bloat of the requiring the uber package.

At a later point we can certainly think about publishing packages that group widgets together by a specific type or use case, but these would most likely just be a `package.json` that has the dependencies on the individual widget packages' (meaning that the imports would be the same as if you'd installed them individually).

**Comment by jjrv** [comment]
@agubler in that case for Github repo organization I like exactly this idea:

- widgets-form
- widgets-layout
- dgrid
- calendar

If the individual widget npm packages really end up having low overhead (not much size difference between an uber-package @dojo/widgets-form or all of its widgets installed from separate packages) then it definitely sounds better to cut them up into individual widgets on npm. It's nice that the @dojo namespace anyway gets installed as its own subdirectory.

Maybe naming the npm packages like `@dojo/widget-form-button` and the meta-package like `@dojo/widget-form` and the Github repo like `dojo/widget-form` would be sensible and discoverable?

**Comment by agubler** [comment]
I think as @dylans mentioned github repo wise we're likely to remain with as few repo as sensible, obviously exceptions have and will be made for complex standalone components such as `dgrid`.

We will still be able to achieve all the publishing combinations we've both mentioned over time. Yes I really like the `@dojo` namespace, it gives a lot of power in terms of how and what we decide to publish in terms of naming.

**Comment by rishson** [comment]
Really good points @agubler @jjrv
So, current thinking is:

Potentially provide some structure in our repo:
```
@dojo/widgets/src/form/text-box
@dojo/widgets/src/layout/split-pane
...
```
and publish as a single package: `@dojo/widgets` (to match repo name)
so you could import as:
`import TextBox from '@dojo/widgets/form/text-box'`
where the nesting mirrors the repo structure.

We could also publish each widget to npm in a flat structure:
e.g.
TextBox published to npm as @dojo/widget-textbox

so you could import as:
`import TextBox from '@dojo/widget-textbox'`

**Comment by rishson** [comment]
OK. I think we have settled on a solution here.
We will *not* be publishing widgets individually to `npm`.
We will *only* publish the uber package to `npm`.

To import a single widget: `import Button from '@dojo/widgets/button/Button';`

Because each widget is a separate module, then when creating a production build (e.g. using `dojo build`), then only the widgets that you have imported will be included in your bundle.

The `widgets` repo will not have nesting of widgets; all will reside under `src`, e.g. `widgets/src/Button`, `widgets/src/TextArea`.

The `widgets` README will nest the widgets in its explanation, but this is the only nesting we shall have.
