### ISSUE TITLE
createMemoryStore should never use size or length as an id

### ISSUE THREAD

**Issue by matt-gadd** [dojo/widgets#20]
https://github.com/dojo/widgets/blob/master/src/util/createMemoryStore.ts#L256

If we get to the end of this long ternary we should throw an error, or at least generate a guaranteed to be unique id, which size is not.

**Comment by kitsonk** [comment]
This is what happens when you hack something together to just get things working. 😉 

Looking at dstore, it didn't actually generate a GUID either, it basically default random number, which of course may or may not result in collisions.  I will abstract this out so that it does provide a GUID when it auto generates one.

**Comment by matt-gadd** [comment]
@kitsonk :), I believe the original MemoryStore in dojo simply uses `Math.random` also. Do we have a guid util in `core` anywhere?

And on a semi related note, do we have an issue to discuss what our plans are in terms of `dstore` or stores in general?

**Comment by kitsonk** [comment]
> Do we have a guid util in `core` anywhere?

No, but I have some previous work in generating a recognised GUID that meets specifications buried somewhere which I will dig out.

> And on a semi related note, do we have an issue to discuss what our plans are in terms of dstore or stores in general?

[dojo/stores/issues](https://github.com/dojo/stores/issues/)

**Comment by kitsonk** [comment]
Issue moved to [dojo/stores #16](https://github.com/dojo/stores/issues/16) via [**ZenHub**](https://www.zenhub.com/)
