### ISSUE TITLE
Potentially remove createStateful as default in createWidgetBase

### ISSUE THREAD

**Issue by matt-gadd** [dojo/widgets#213]
**Enhancement** 
Given `properties` are now nearly complete, it seems like having internal `state` may no longer be required for the majority of simple widgets, as they can be represented by `properties`. If the author wanted to keep internal state they would mix `createStateful` in

**Comment by agubler** [comment]
I believe a mixin (`internalState`) that extends `createStateful` and provides invalidation on `setState` would provide the functionality required mixin behaviour. 

Consumers can add the mixin in order to provide internal state, however any auto properties --> state update would need to be manually wired on the `properties:changed` event.
