### ISSUE TITLE
Move `widgets.css` file to examples directory

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#240]
**Enhancement** 

To dissuade dojo 2 adopters from using `widgets.css` we should look to moving it into the `common/example` directory.

**Comment by bitpshr** [comment]
I'm in favor of this. I never liked having a `widgets.css` file. It sort of implies a symmetry with the root `index.js` module that exposes all components, but that's not totally accurate: using `index.js` is fine since downstream JS code will be built and optimized, but using `widgets.css` will arbitrarily include all CSS files regardless of whether they're actually used.
