### ISSUE TITLE
Reusable Contained Widgets

### ISSUE THREAD

**Issue by kitsonk** [dojo/widgets#275]
**User Story**

As a developer, I want to take existing widgets and _combine_ them into a single widget which can then be used at several places within an application.

**Specific Use Case**

I need to create a reusable dialogue within my application.  This dialogue needs to have a customisable message with an _OK_ and _Cancel_ button that are positioned appropriately according to our style guide.  I want to provide this widget to another team member, passing only a message property with an `onOk()` and an `onCancel()` property methods.

**Comment by smhigley** [comment]
My take on creating composite widgets, broken up roughly into two general categories:
- Creating the containing widget
- Theming / styling component widgets

## Creating the containing widget
The reusable dialog in the sample user story follows what seems like a fairly typical pattern of composite widgets: one containing widget with multiple child widgets. I can see two basic approaches to creating the custom widget (assuming an inheritance approach based on https://github.com/dojo/widgets/issues/266#issuecomment-324901905):
1. Extend WidgetBase with Dialog as a child
2. Extend Dialog directly

For this example in particular, extending WidgetBase seems like the obvious choice, since tight control over the API is a priority, and it doesn't need to re-implement much of `DialogProperties`. It could look something like this:
```typescript
interface ConfirmationDialogProperties extends WidgetProeprties {
    open?: boolean;
    onCancel?(): void;
    onOk?(): void;
    onOpen?(): void;
	onRequestClose?(): void;
}

class ConfirmationDialog extends WidgetBase {
    protected render() {
        return w(Dialog, {
            open,
            onOpen,
            onRequestClose
        }, [
            this.children,
            w(Button, { onClick: onOk }, [ 'OK' ]),
            w(Button, { onClick: onCancel }, [ 'Cancel' ])
        ]);
    }
}
```
The only drawback I can see is that it needs some of `DialogProperties` essentially copy-pasted to its own properties. With another more complicated widget like ComboBox, a wrapping widget would need to pass down something like 10-12 properties to preserve basic funcitionality. There's already an example of this in TimePicker, which wraps ComboBox and re-implements and directly passes through most of ComboBox's properties interface.

Even with the necessary duplication of properties, it still seems better to wrap Dialog than extend it. This allows the author to limit the available properties and have tighter control over the resulting widget. However, this is only the case when the aim is to create a more specialized widget with fewer customization options, not when extending functionality.

I think it's worth explicitly talking about how and when to extend widgets vs. when to wrap them. My initial thought is to think about all widgets as falling into two categories with the following characteristics:

**Widget building blocks**
- Includes all widgets in `@dojo/widgets`
- Should be _flexible_: i.e. easy to customize with properties or extend to add functionality
- Unopinionated about appearance (within reason)

**Higher-order widgets**
- Tightly controlled, with a limited set of properties that are mostly limited to what is necessary for widget functionality (e.g. `open` and `onRequestClosed` in this example)
- Opinionated about layout, potentially about other aspects of visual style as well
- Not built to be extended

Thinking about widgets in two explicit levels should also help limit the problems involved in too many layers of class inheritance @paul mentioned in [his comment](https://github.com/dojo/widgets/issues/266#issuecomment-324901905). If only widget building blocks should be extended, then the max layers of complexity should be three: higher order widget > extended base widget > base widget.

This dialog use case is a perfect higher-order widget example, since it provides a very limited set of properties and no customization. Any changes in the widget (e.g. displaying only an "OK" button and no "Cancel" button) would necessitate creating a second higher-order widget.

The current Timepicker widget is a little harder to classify. It currently wraps ComboBox but doesn't limit customization, and adds properties instead of limiting them. I think the best pattern would be to create a base widget that both ComboBox and Timepicker extend, but failing that I think it would actually be better for Timepicker to extend ComboBox, and ComboBox to provide more hooks to allow extension.

## Widget-specific visual styles
There are only two ways to customize the style of a component widget:
1. Extend the widget with a new `@theme` directive
2. Use `extraClasses` and give up future theming

### Extension + @theme
The benefit of the first approach is it preserves the ability to theme all parts of the resulting composite widget. The drawback is an explosion of css module files, and the need to extend every variation of every component widget. For example:

**In CustomDialog.ts**
```typescript
@theme(customDialogCss)
class CustomDialog extends Dialog {}

@theme(buttonConfirmCss)
class ButtonConfirm extends Button {}

@theme(buttonCancelCss)
class ButtonCancel extends Button {}
```

**File structure**
```
- customDialog/
    - styles/
        - customDialogCss.m.css
        - buttonConfirmCss.m.css
        - buttonCancelCss.m.css
    CustomDialog.ts
- themes/
    - customTheme/
        - customDialogCss.m.css
        - buttonConfirmCss.m.css
        - buttonCancelCss.m.css
```
(the actual non-themed confirm/cancel button css may end up their own folders, but this gives a general idea of how many css files are needed to create and theme this use case)

### extraClasses
Using `extraClasses` would mean the entire custom dialog widget would only need a single additional css module file, but none of the styles added through `extraClasses` could be themed. However, if the idea behind higher-order widgets is that they are opinionated about not only layout but also all visual styles, then `extraClasses` may actually be the best solution.

The other drawback, in addition to being unthemeable, is styles applied with `extraClasses` conflict with existing classes' styles instead of replacing them. This means if a different theme were passed in, it might affect `extraClasses` in brittle or unpredictable ways.

## Conclusion
It seems like a good idea to start documenting patterns best practices for higher-level widgets like the confirmation dialog separately from generic widgets.

For styling I lean towards `extraClasses`, but the drawbacks (leaky, unthemeable) are serious enough that I'm still unconvinced.

**Comment by bitpshr** [comment]
To summarize, when creating a reusable, specialized version of a component, like a Dialog with specific styling and children, combining components directly (either as children or siblings) within a common parent is a good approach. This is essentially a non-functional Dojo 2 way to create higher order components: wrap them in a common parent and expose properties on that parent to influence the children. This doesn't involve extension and properly respects the APIs that are exposed by widget authors.

Action items:
* ~~Create a ticket to add a tutorial for this content~~ dojo/dojo.io#290
* Close this ticket
