### ISSUE TITLE
Pixels vs relative units

### ISSUE THREAD

**Issue by rishson** [dojo/widgets#35]
Age old debate, and one I'm sure that we are all bored of, but we need to be consistent across our widgets regarding sizing in `px` vs `em` vs `rem`.
Things we need to decide upon:

- are there any `a11y` implications of this choice?
- is sizing a single Dojo 2 component on a website a priority for us, and how should we allow this?
- when we consider our own themes, how do we want to work with breakpoints (media queries) and sizing, e.g. breakpoints in `px` or `em` or `rem`...

**Comment by tomdye** [comment]
@bitpshr @smhigley Would be good to get your thoughts on this. I think it's important to be consistent whatever we decide.

**Comment by bitpshr** [comment]
If we use `rem` but don't set default font sizes on the `html` element (which I don't think we should be doing, see #21), we could get inconsistent sizing in different apps. I vote for `px`.

**Comment by rishson** [comment]
"inconsistent sizing across different apps" @bitpshr don't understand.

**Comment by rishson** [comment]
Happy to be corrected, but (whilst browser zooming is fine with `px`), if the user sets their `font-size` in their browser, then if we specify in `px` then we effectively ignore their wishes. Also, IIRC, FF's `zoom text only` will also break if we use `px`.

**Comment by bitpshr** [comment]
`rem` units are relative to the `font-size` of the `<html>` element on a page. This means that if our components are used in one application that has a base font size set of `14px` and another application with a base font size set of `16px`, our components would have different font sizes between the two pages.

Everything would still maintain proportional font sizing, so maybe this is OK?

**Comment by rishson** [comment]
Yup - I get how `em` and `rem` work 😄 It was the 'inconsistent' term that threw me. So lets take this further. If a user sets the default font-size (or relies on `rem` taking the browser default of 16px), then I'm assuming that they would expect us to honour this request (and if we set every widget's font size to `1 rem` then we can do this. If we specify in `px` then we ignore their wishes (for the reasons I _think_ still apply - as noted above re: `font-size`). If we specify in `em` for each widget, then we also allow the user to make a single widget have different spacing (an ability you loose if you use `rem`). I mean, you can always use `overrideClasses` but I was hoping to resolve without code-level stuff.

**Comment by smhigley** [comment]
I agree with @bitpshr, I would be mostly against `rem`, since I don't like the idea of individual widgets relying on the `font-size` set on `html`. I like using `em` for non-font values like `padding`, `margin`, etc., but it's basically a style choice of whether or not you think all dimensions of a widget should scale up equally (@itorrey may want to weigh in). The result would be something like:
```
:root {
  --base-font: 14px Roboto;
}

/* button/button.css */
.button {
  font: var(--base-font);
  padding: 0.5em 1em; // or this can be a --small-widget-padding var
}
```

There are no accessibility concerns whatever way we choose. All modern browsers (and even not-so-modern ones) handle zooming `px` font sizes just fine. People who for some reason decide to delve into advanced settings to change the browser's default stylesheet are savvy enough to deal with the fallout (and probably statistically insignificant)

**Comment by rishson** [comment]
@smhigley thanks. I must admit that I've always worked under the assumption that '`em` = good for `a11y`, `px` = bad 'cus *TEXT-SIZE*' - but having [read](https://mindtheshift.wordpress.com/2015/04/02/r-i-p-rem-viva-css-reference-pixel/) [around](https://developers.google.com/speed/docs/insights/UseLegibleFontSizes) a bit more today it seems like this is no longer true. It could also be argued that `px` is better for `a11y` because visually impaired users are more likely to increase font size at the OS level (scale settings), rather than the application (browser) level. In this case, the CSS ref pixel may be a better tool for adopting to user's preferences.

**Comment by rishson** [comment]
So can we get consensus on what to use for:

- font sizes
- padding/margins/placement
- breakpoints

My current opinion is:

- `px`
- `em` if it makes sense (proportional design) else `px`
- `px` 

My breakpoint opinion is again based on previous behaviour/learning (and somewhat contradicts my previous `em` preference). I see lots of articles about `em` MQs and designing to fit content rather than the viewport, so would like to have my thinking on this challenged as well 😄 .
Previously, I always just put `<meta name="viewport" content="width=device-width, initial-scale=1">` in the page and had `px` breakpoints and it 'worked fine for me' ™️ but I like to understand this area better.

**Comment by tomdye** [comment]
Glad we seem to have reached a sensible decision here on `px` units. Are responsive breakpoints something we plan to provide? I would imagine that responsive layout is an app concern, not a widget concern.

**Comment by dylans** [comment]
> Are responsive breakpoints something we plan to provide? I would imagine that responsive layout is an app concern, not a widget concern.

I can imagine scenarios where the widget itself might want to respond to how much space it has available, rather than screen width. For example, a tab container without enough width to show all tabs might switch to having a dropdown list of all tabs and left/right navigation to slide tabs around? (which for what it's worth is my favorite feature of Dojo 1's TabContainer, e.g. make it behave like Firefox for tab management ;) ).

**Comment by tomdye** [comment]
Yes @dylans, that was what I was getting at.

**Comment by rishson** [comment]
Widgets would probably care about breakpoints in the following situations:

- my content is _now_ longer than a stated chars-per-line, perhaps I should ellid, wrap etc
- wow, the real estate is getting low, maybe I'll hide my icon and just show text (or hide text and just show icon..)
- things are getting cosy, maybe I should start to stack my content 

Otherwise, how else will our widgets be reponsive, mobile-friendly, etc?

**Comment by bitpshr** [comment]
@rishson's [thoughts above](https://github.com/dojo/widgets/issues/35#issuecomment-281300829) sound good to me. As for breakpoints, we should probably look at what the ultra-battle-tested CSS frameworks do, like [Bootstrap](https://v4-alpha.getbootstrap.com/layout/overview/#responsive-breakpoints). I know a lot of research has gone into their chosen breakpoints, so maybe we just lift those?

```sass
// Small devices (landscape phones, 576px and up)
@media (min-width: 576px) { ... }

// Medium devices (tablets, 768px and up)
@media (min-width: 768px) { ... }

// Large devices (desktops, 992px and up)
@media (min-width: 992px) { ... }

// Extra large devices (large desktops, 1200px and up)
@media (min-width: 1200px) { ... }
```

**Comment by rishson** [comment]
@bitpshr so the most comprehensive and up-to-date list I've found is [here](https://css-tricks.com/snippets/css/media-queries-for-standard-devices/). However, I'd probably recommend simplifying and not being device specific, e.g.

```
x-small
small
medium
large
x-large
```
similar to what material design [does](https://material.io/guidelines/layout/responsive-ui.html#).

**Comment by bitpshr** [comment]
Seems fine to me. I think most components will only use one or two of these breakpoints anyways. I agree we should avoid device specificity . I vote for Bootstrap or Material breakpoints. They are pretty close to each other. So riffing off simplified Material breakpoints, maybe something like:

```sass
// x-small
@media (max-width: 600px) { ... }

// small
@media (max-width: 960px) { ... }

// medium
@media (max-width: 1280px) { ... }

// large
@media (max-width: 1600px) { ... }

// x-large
@media (min-width: 1601px) { ... }
```

**Comment by smhigley** [comment]
As a general rule, I favor component-specific breakpoints over global breakpoints. I can see how a set of app-level breakpoints would be useful for layout widgets and possibly typography, but would we use them at all in specific widgets? I've usually found that high-level breakpoints often don't match when a specific component might need to switch layout. On the other hand, we have no control over where components are used (full width, half-page, two columns, etc), so I could be convinced that it's better not to be too specific with tailored breakpoints in this case.

For `max-width` vs. `min-width`, I still prefer `min-width`. Mobile-first breakpoints aren't there to prioritize the mobile experience -- it's because mobile layout is usually simpler than desktop layout, so starting there means fewer styles to override and cleaner css.

I _think_ px breakpoints are now fine a11y-wise, but I would like to test it in all browsers. I think I remember something about Safari handling them incorrectly when zoomed in (e.g. a 400px breakpoint at 2x zoom should be triggered at 800px, but is still 400px in Safari).

Also, you and me both, @dylans :)
> I can imagine scenarios where the widget itself might want to respond to how much space it has available, rather than screen width.

If I had a penny for every time I wished I could do this, I'd have... well, maybe a few dollars.

**Comment by bitpshr** [comment]
I think the global breakpoints would primarily be used for layout components, especially ones that are fixed or page-wide, like a Dialog, SlidePanel, or Menu. I agree that most other components won't want to update their layout blindly based on screen width. Maybe we need some mechanism to determine available space for a given component?

Also, I almost always have more complicated mobile layouts, so I use `max-width` so I override less. I don't really care either way though. As you said, I think the breakpoints will be used sparingly.

**Comment by smhigley** [comment]
It looks like the px breakpoint issue has been fixed in the latest version of Safari, so it should be fine.

I'm fine with `max-width` here. For basic stuff, it shouldn't matter much either way.

**Comment by dylans** [comment]
> If I had a penny for every time I wished I could do this, I'd have... well, maybe a few dollars.

:)

Probably the other things to consider which may be relevant or may be an orthogonal concern is certain styles that really should vary based on touch vs non-touch, e.g. making sure that buttons or other smaller form controls are big enough to be tapped by a finger or thumb. This often changes the relative ratio or proportion between sections of a widget.

**Comment by rishson** [comment]
So decision is:
- `px` for font-sizes
- 'px' or `em` for padding/margins/placement (use as appropriate).
