### ISSUE TITLE
Tabs have no background color

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#353]
**Bug ** 

![screenshot 2017-11-01 17 26 10](https://user-images.githubusercontent.com/814453/32287792-cc077120-bf29-11e7-8cf5-da4dafdb62f7.png)

This may be intentional

**Comment by tomdye** [comment]
@bitpshr @smhigley thoughts please?

**Comment by smhigley** [comment]
I think it makes more sense if you imagine it on a slightly off-white background, where it may look weird if that style of tab has a bg color. But again, I'd defer to Scott.

**Comment by bitpshr** [comment]
This was intentional for the reason @smhigley mentioned. Because the tabs are only styled with a border on the bottom, they should be able to be applied over top of any background and mesh with the underlying page. The off-white background example is more applicable, or any other realistic background color other than red. 

If the tabs had aesthetics that were more "contained", a look that had a clear border around all buttons and content where it was apparent that the tabs didn't blend in with the surrounding page, I'd say we should be explicit with background coloring.

I vote we close this issue.

**Comment by smhigley** [comment]
Closing in favor of leaving tabs transparent
