### ISSUE TITLE
Text color on select / combobox are a different colour

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#355]
**Bug** 

![screenshot 2017-11-01 17 28 19](https://user-images.githubusercontent.com/814453/32287897-1d35ced4-bf2a-11e7-9628-4e85193934ba.png)

I would expect `Select` to have the same font styling

**Comment by smhigley** [comment]
@tomdye I believe this is related to #298. Select currently doesn't support a placeholder (since native select doesn't support one), so the dark text in Select is an actual value, while the greyed text in Timepicker/Combobox is the placeholder text. If you choose a value for the latter widgets, you'll see the text should match.

The plan is to add placeholder support to custom Select widgets, which should solve this as well.

**Comment by tomdye** [comment]
thanks for the update @smhigley . is it worth keeping open for future tasks?

**Comment by smhigley** [comment]
Hm, I think it's a duplicate of #298, since it's not actually the styling that differs but the existence of a placeholder. I do plan to get a PR in for both today though, so not a big deal either way.

**Comment by tomdye** [comment]
ok, no worries, happy to close
