### ISSUE TITLE
Delivery of icons

### ISSUE THREAD

**Issue by rishson** [dojo/widgets#36]
@smhigley @bitpshr @tomdye another topic for investigation.
We will have need for icons in our widgets.
How will we ship these icons? (icon font, svg, other..)?
If icon-font:
- will we create our own or use a 3rd part icon font?
- how will we use within css?
- how will we deal with FOUT issues on load, fallback and `a11y` concerns?

If svg:
- where will we get our icons from?
- should we consider animated svgs?
- is the 'get parent colour' issue, still an issue?
- should we bitmap or rely on `http2` for performant loading?

Current opinion (please challenge):
- [use](https://cloudfour.com/thinks/seriously-dont-use-icon-fonts/) svg (its awsome), with suitable [fallbacks](https://www.filamentgroup.com/lab/bulletproof_icon_fonts.html)

Can I get your current preferences and reasoning please?

**Comment by tomdye** [comment]
I believe that @itorrey is a big fan of material design icons, otherwise i'd say why not use font-awesome as it's pretty much industry standard. I also don't see why this is of concern to widgets as it's likely down to an app developer utilising our widgets to supply the `htmlz` to render their desired fonts rather than us providing them.

**Comment by dylans** [comment]
In the past there was a major issue with svg on iOS (we learned this the hard way on sitepen.com when we rolled out the current design, and we could crash Safari after a few page views as the memory for background svg was not released). I assume this was fixed, but I would suggest we run some mobile performance tests or find a recent study to see if the best practice has changed recently.

**Comment by rishson** [comment]
I was imagining that we would provide icons for things such as:

dialogs (warning, error, info icons)
icon buttons (with a nice set of icons)
_basic_ icons (dropdown/titlepane arrow, mand/invalid form element indicators, searchInput icons)...

The problem with providing icons is that you can't please everyone, so you are always running to stand still. The problem with not providing icons, is we have to respond to support issues all the time, for why _their_ chosen icon set does not work with Dojo 2, or in browser x.

**Comment by rishson** [comment]
@dylans agree. A solid perf comparison of an icon font set and svg is needed.
I dislike "lets use x because its popular" - bear in mind that FA5 (May 2017) will have svg support, fa vs svg is not really the battle anymore.

**Comment by tomdye** [comment]
Fair @rishson , I see what you mean now. So `font-awesome` or `material` icons would likely provide what we need and a decent user experience. Utilising `material` would most likely align with @itorrey designs. Either way it would be good to expose the icons for users to utilise in their own apps via the original intended class names etc...

**Comment by rishson** [comment]
FA5 has a pre-release (for a kickstarter donation) so we could start to incorporate now, but my original question still needs opinions: '3rd party icons or create our own' @itorrey ?
@tomdye I'd see something like a full set of icons in our base themes, a set of material icons in our material theme (if we do one)...

**Comment by tomdye** [comment]
sure @rishson , I don't think we should maintain a mapping of `dojo-save-icon` so `fa fa-save` though for example, it gets messy to maintain and confusing for our users.

**Comment by smhigley** [comment]
A couple additional questions I have are:
- Do we go with using separate nodes for icons, or use pseudo-elements?
- Should we allow users to specify icons by passing in HTML entities to a property, or words like `save` that map to a specific icon (or svg)? The first is more flexible, but the second looks prettier and gives us more control.

Other than that, @tomdye, I'm not sure why we'd need to map dojo classes to fontawesome classes. Wouldn't we have the correct styles in our own css? Or is it worth it to allow people to use features like rotation, size, and spin animation through `fa-*` classes?

I've tried SVGs instead of icons in the past, so I'm comfortable with both. There are certainly a lot of arguments for svgs (easier a11y for one), but it seems like it would present an extra challenge for self-contained widgets. I assume we won't be able to use the standard `svg use` elements for a number of reasons, so we'll need inline svg -- are there any concerns about the lack of caching and dom weight if a large number of icons are used?

**Comment by tomdye** [comment]
@smhigley I said `i don't think we should maintain a map`. Main thing is to ensure it's strictly typed such that you get the nice intelisense when specifying an icon type etc and that it's accessible.

**Comment by smhigley** [comment]
Decision:
- Use icon fonts over svg sprites or inline svg
- Have a themeable variables file for keyword -> css entity
- ignore fallbacks for now (browsers now keep text invisible before font load, so FOUT is less of an issue)
- Have a small set (maybe 20-ish) icons by default
