### ISSUE TITLE
Form elements and submitting forms

### ISSUE THREAD

**Issue by rishson** [dojo/widgets#38]
If you had a `form` widget, with a child `textInput` and `checkbox` widgets, how would we collect up the current state of the children on an `onsubmit` event of the form?
Specifically, I think we need to think about how this would work if we made our form elements into uncontrolled components.

The answer may be simple, but I'd like to know the way forward so I can add 'form widget support' as a spec item for the form element issues.

@smhigley @bitpshr @tomdye - another one for you lot i'm afraid 😄

**Comment by bitpshr** [comment]
Why should our form components be uncontrolled? React and other libraries [use controlled form components successfully](https://facebook.github.io/react/docs/forms.html#controlled-components). It makes sense to me that the parent component and child form component should always be in sync, and that the parent component is the single source of truth, not the underlying raw DOM. This is sort of the definition of unidirectional flow. I vote for keeping all our components controlled, form or not, unless it's absolutely necessary for them to be uncontrolled.

@tomdye brought up a concern of asynchronous external state. Let's say I type a value into a TextInput and need to store this value in an asynchronous store in the parent component. In both cases, the UIs can update immediately and store external state asynchronously without issue:

### Uncontrolled TextInput example

TextInput Component
```ts
onBlur(event: Event) {
    this.properties.onBlur && this.properties.onBlur(event.target.value);
}

render() {
    return v('input', {
        onblur: this.onBlur
    });
}
```

Parent Component
```ts
w(TextInput, {
    onBlur: (value: string) => {
        asyncStateUpdate(value);
    }
})
```

### Controlled TextInput example

TextInput Component
```ts
onBlur(event: Event) {
    this.properties.onBlur && this.properties.onBlur(event.target.value);
}

render() {
    return v('input', {
        value: this.properties.value || '',
        onblur: this.onBlur
    });
}
```

Parent Component
```ts
w(TextInput, {
    value: this.state.inputValue,
    onBlur: (value: string) => {
        this.setState({ inputValue: value });
        asyncStateUpdate(value);
    }
})
```

Note that in the controlled example, the UI doesn't have to wait to update until the asynchronous operation completes, so callback order makes no difference. If an error occurs, the UI will be reverted, the same way it would be in the uncontrolled example.

**Comment by rishson** [comment]
OK - thanks @bitpshr for the really clear and detailed response. 👍 
Ignoring the async state issues, let me elaborate and paraphrase to make sure I fully understand:

If we had a `form` widget, then if all the form's 'form input widgets' (inputs, textareas..) are controlled, then we are golden, because the parent (`form`) has their state anyway and is the source of truth.
Does my concern still stands if a user (rather than us) chooses to make a 'form input widget' uncontrolled (for whatever reason)? Do you think we should not initially support uncontrolled widgets in our `form` widget?
In order to support uncontrolled form input widgets, we would need a way for the `form` to fetch the latest state out of the uncontrolled form input widgets, like react's `refs` - right? Is this something that you think we should look to do?

**Comment by bitpshr** [comment]
I think your concern does still stand for user-created uncontrolled components, or any Dojo 2 component we create in the future that has to be uncontrolled by necessity. I see two options for getting values out of uncontrolled children:

**Use property callbacks and cache values when they change.**
If a parent component needs to keep track of the values of uncontrolled child components, the parent can pass in a callback property, such as `onChange`, `onBlur`, etc., and cache the value whenever it changes. This is similar to how controlled components would be handled, the only difference being that the value wouldn't be passed back into child.

**Use a feature similar to React's `refs` to get values on demand.**
Using this approach, a parent could get values of children whenever it needed to. I think we'd need to make it so the reference could be mounted to either a child DOM element _or_ a child component instance, since a component's value may not always be represented fully by the DOM.

**Comment by rishson** [comment]
As agreed:
For beta we will have a `form` widget that works with controlled components only.
We will document this restriction.
At a later date, we will raise an issue on `widget-core` for a way to handle uncontrolled components also.
