### ISSUE TITLE
TabController and Tab custom element definitions not working

### ISSUE THREAD

**Issue by maier49** [dojo/widgets#387]
**Bug** 

`TabController` and `Tab` custom element definitions are not working properly, and TabController's tag name is mismatched with the class name.
Package Version: 0.2.2

It's possible that I am not using these together properly, but I tried as many different variations as I could think of as well as setting them up programmatically and declaratively. Essentially the below code doesn't create a functional tab container

```
<dojo-tab-pane activeindex="1">
  <dojo-tab key="1">Content</dojo-tab>
</dojo-tab-pane>
```

Related to this: the `TabController`'s custom element definition, found in `createTabControllerElement`, specifies its tag name as `dojo-tab-pane`, which is inconsistent with the widget class and the definition file's name.

**Comment by pottedmeat** [comment]
This one is pretty complicated. Basically, in our custom element handlers, we wrap the actual widget instances so that they render through the custom element system.

The problem seen here is that some widgets need access to the child widgets they contain and the properties of those child widgets. Currently, neither children nor their properties are available.

What I've done is to create another wrapper that wraps the `w(...)` call in a way that acts as a proxy for the `children` and `property` values that would normally have been passed to a `w(...)` call.

These can be found at the following branches:

https://github.com/pottedmeat/widget-core/tree/bug-attach-custom-elements
https://github.com/pottedmeat/widgets/tree/bug-attach-custom-elements

I've added a test page in `widgets/src/tabcontroller/example/element.html`. It looks weird because the default `align` value put the buttons below the content. It's currently able to change the `tabIndex` (switch tabs) but the events aren't firing.

**Comment by dylans** [comment]
Related to https://github.com/dojo/widget-core/issues/809

**Comment by dylans** [comment]
Fixed with the RC1 custom elements refactor.
