### ISSUE TITLE
How to call Textarea's focus() method in custom widget

### ISSUE THREAD

**Issue by xiaohulu** [dojo/widgets#417]
Package Version: 0.2.1

**Expected behavior:**

how to call element.focus() in my custom dojo2 widget?

**Actual behavior:**

I write a widget, contains a `div` and a `textarea`, when click left mouse on `div`, the handler call the `textarea.focus()` method, but now I can not find how to call `focus` method in my dojo2 widget.

**Comment by smhigley** [comment]
@xiaohulu this is actually an area we're currently working on. The basic issue is that since Dojo 2 is reactive and provides no direct access to widget instances, it's not possible to directly provide a `.focus()` method on the widget. We're working on creating a tool that will allow you to send focus to widget children.

For now, the only way to accomplish this is to use the `onElementCreated` and `onElementUpdated` lifecycle hooks:

```
protected onElementUpdated(element: HTMLElement, key: string) {
	if (key === 'parentKey' && otherConditions) {
		const textarea = element.querySelector('textarea') as HTMLElement;
		textarea && textarea.focus();
	}
}
```

Both these hooks will be removed in the future, and reaching into a child widget's DOM like this is strongly recommended against. However, if you absolutely need to focus a child widget, this is the only way to do so until we finish our focus tool.

Hope that helps!

**Comment by smhigley** [comment]
If you would like, you can track our progress in the issue in `@dojo/widget-core`: https://github.com/dojo/widget-core/issues/729

**Comment by xiaohulu** [comment]
Ok, thanks.
