### ISSUE TITLE
Combo / Time picker / Listbox does not have a max height and are not scrollable

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#443]
**Bug** 

The listboxes presented by timepicker / combo box etc do not have a max height and as such they can run right off of a screen. This makes it very hard for a user to get to the value they require.
They also do not have a scrollbar and as such you cannot scroll through results without losing your place on the page.

![screenshot 2018-02-02 14 19 55](https://user-images.githubusercontent.com/814453/35737669-3a88c5fc-0824-11e8-8aab-31071192023f.png)

**Comment by smhigley** [comment]
I set a `max-height` to test keyboard scrolling behavior in development, so the requisite styles and behavior are there. All it would need is a `max-height` style. I'm leery of putting this directly in our theme CSS though, since the best max-height can be very context-dependent.

Would you be OK with adding this to our examples, or do you want it directly in the theme? Alternatively, do you think we need to add logic to the widget itself to prevent it going off-screen?

**Comment by tomdye** [comment]
I think that it needs to `just work` as expected out of the box. Perhaps a max height property as you suggested defaulting to a sensible value.

**Comment by tomdye** [comment]
Issue moved to [dojo/themes #7](https://github.com/dojo/themes/issues/7) via [**ZenHub**](https://www.zenhub.com/)
