### ISSUE TITLE
input widgets are full width

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#447]
**Bug** 

At present, all input widgets are full width of parent. This makes them difficult to quickly place on a page. Dojo 1.x input widgets had a preset width that make them quick and predictable to place on a page. Dojo 2 input widgets should do the same.

**Comment by smhigley** [comment]
I think some assumptions about best CSS practices and default styles have changed since Dojo 1.x styles were created. Right now creating an input with a set `max-width` would probably be seen as unexpected -- for example, other style frameworks like Material and Bootstrap leave inputs at `100%` width with no max and control the width through parent elements.

You're right that our showcase and example pages should implement this, though (maybe you've already done this for showcase, I haven't looked yet).

**Comment by tomdye** [comment]
So we’d expect users to create a wrapping div or something to achieve this? I feel that they should all have a default width so they line up nicely.

**Comment by tomdye** [comment]
We will not be doing this as the current approach allows the most flexibility
