### ISSUE TITLE
What is a popup Button?

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#456]
**Bug** 

Button implementation contains the ability to add a `popup` property, yet there is no popup and no separate `onclick` event etc for the dropdown / popup icon to the side.
This is very confusing to the user and should likely be removed.

![screenshot 2018-02-02 14 51 37](https://user-images.githubusercontent.com/814453/35739146-95f9808a-0828-11e8-8d9a-50e459e3df02.png)

**Comment by smhigley** [comment]
A popup button is a semantic and stylistic change. It doesn't (and can't) handle opening another widget itself, but it's the best choice if you need a button that opens a tooltip or dialog.

We should probably have some better docs around this, or include a tooltip in the example. We could also think about removing it since `aria: {}` is a thing now, but it does seem like a common button use case (and one that developers with little a11y experience would likely forget to implement).

**Comment by smhigley** [comment]
On your note about separate click events for the apparently divided button -- I actually think combined two-in-one buttons like that are confusing from both a general UX standpoint and an a11y one, but I agree that it looks like it might act like that. I think that might be something to revisit in the theme styles, so it's more clearly la single button.

**Comment by tomdye** [comment]
FYI. The similar button in dojo 1.x has two separate events.

**Comment by agubler** [comment]
@smhigley @tomdye What's the status of this?

**Comment by smhigley** [comment]
The earlier answers are still valid. I could see an argument for making the button more visually a single click target, but that would likely be part of a broader design review.
