### ISSUE TITLE
User-provided i18n bundles

### ISSUE THREAD

**Issue by dylans** [dojo/widgets#507]
**Enhancement** Need to determine workflow to apply user provided resource bundles for our widgets.

**Comment by mwistrand** [comment]
Rather than updating `@dojo/widgets` to allow user-provided localized messages, a better long-term solution might be to allow a custom property on `I18nMixin`:

```
// override an entire bundle
w(Calendar, {
    overrideBundle: {
        locales: { .... },
        messages: { ... }
    }
});

// extend the bundle with support for additional locales
w(Calendar, {
    overrideBundle: {
        locales: { .... }
    }
});
```

If this is route we'd like to go, I already have a [`widget-core` branch](https://github.com/mwistrand/widget-core/commit/3c15e5476f1e0da20a205ce0a0e9a0edf1a50457) that's nearly PR-ready.

**Comment by mwistrand** [comment]
Closing in favor of dojo/widget-core#901
