### ISSUE TITLE
Specifying max/min selectable date in Calendar?

### ISSUE THREAD

**Issue by krezovic** [dojo/widgets#538]
**Enhancement**

Package Version: master

Is it possible to add min/max selectable date constraints to the calendar. It would be nice that we have something like that, similar to what DOJO1 date picker calendar had.

**Comment by schontz** [comment]
I have a PR in the works on this one. In my basic testing it works but it will need a slew of unit tests for real validity.

One thing that this brings up is the need for a new attribute and class name for `CalendarCell`s, e.g. `selectable`. Using `disabled` won't do since that really means 'not the current month'.

**Comment by schontz** [comment]
You can see the PR in progress here:

https://github.com/dojo/widgets/compare/master...schontz:538-calendar-max-min-selectable-date?expand=1

**Comment by aciccarello** [comment]
I started on this from the above branch. Just fixes the merge conflict but I will see what else needs to be done.

https://github.com/dojo/widgets/compare/master...aciccarello:538-calendar-min-max?expand=1

**Comment by schontz** [comment]
And scene!

**Comment by schontz** [comment]
Nice! Thanks for running with this, @aciccarello.
