### ISSUE TITLE
Add font awesome for icons and create icon.css

### ISSUE THREAD

**Issue by rishson** [dojo/widgets#54]
Tasks:

- [ ] add fa to our codebase
- [ ] implement in at least 1 widget

Questions:
Where should we implement an icon to test the integration?
Do we need to replace the down and up arrows on `ComboBox` and `TitlePane` or keep as text content?
Should we use as few icons as possible or use in as many places as possible for a consistent look and feel?
We could always add 'type' to `Dialog` e.g. `error|warn|info` and have nice icons by the dialog content header..

**Comment by tomdye** [comment]
`type` for dialog should be optional, but should utilise the icons we provide for a consistent look and feel. The same goes for the combo box and title pane in my mind as this will allow the icons to be swapped out for theming purposes.

As discussed previously we need to decide how we're going to approach the naming and typing of icons. We'll likely need to abstract away the `fa-` that font-awesome uses in order to allow simpler switching of icon sets. 

The whole process of setting up an icon font to be used may need a script / build step but it would only need to be ran each time icons were updated.

**Comment by kitsonk** [comment]
Other considerations:

Do we include a custom build of FA just for the icons we use?
Is FA the right way to have a level of "efficiency" versus other forms of icons that might be more narrow targeted?
Should icons be abstracted into a theme?  This seems to imply tight coupling at a lower level than a theme.

**Comment by rishson** [comment]
So I would advocate using something like icomoon or a custom sprite/font generator to include just the icons we need for our own widgets.
We plan to include a base set of icons with classes to apply them - which can be used x-theme.
If we were to do a material design theme for example, then we would need to include the relevant icons for this theme also.

**Comment by tomdye** [comment]
Valid points @kitsonk 
@rishson I think it's a toss up between efficiency and providing a large enough set of icons to be useful.

**Comment by rishson** [comment]
To be clear, I'm not advocating having classes for all fa icons, just the ones we use.
If a user want to add another icon font, sprite etc to their app, then they can do that as well.

I've seen some toolkits have an `<i>` or `icon` widget, and we could contemplate doing the same if we felt it held any real value to the user.

**Comment by tomdye** [comment]
I made a start at that previously @rishson. Happy to pick it ip again. We previously discussed how we could provide intelisense for the `icon-type` attribute.

**Comment by tomdye** [comment]
I think we should create and use an `icon-widget` that has a base css providing all the icons we wish to use across the application. These can then be `themed` using the current `Themeable` pipeline giving us a flexible system.

**Comment by rishson** [comment]
I'm coming round to your `icon` widget idea.
How about:
beta 1 - we write an `icon` widget, it takes a `name` prop that specifies the icon to show (from the full range of fa.
The uber `widgets` package can bundle the web font.
We can have an `icon.css` file that uses the fa unicode vals for `content` or somehow ref the `fontawesome.css` somehow??

beta 2 - we look into how we would supply just the icons needed per-widget (for when we publish each widget individually) so, `base64` encode, or use svg version (v5) ...

**Comment by tomdye** [comment]
Sounds good @rishson . I'll crack on with it in the morning. Did we acquire FA5 yet or will we just use FA4? Shouldn't think it's a big deal eitherway.

**Comment by kitsonk** [comment]
Sounds reasonable too... isolates the whole thing.

Longer term, we need to consider the build implications, like we have with CSS and other tech to ensure that there is an optimised set of icons that get emitted.

**Comment by tomdye** [comment]
**Have played around with a POC for this and came up with some *pros* for having an icon widget.**

- easily themed via the `ThemeableMixin` process
- standardised usage across the suite of widgets
- single reference point for `icon types`
- can provide consistent API for sizes and colours

**Sample usage**

``` typescript
import Icon, { icons, modifiers } from '../../icon/Icon';

w(Icon, {
	type: icons.iconCheckCircle,
	modifiers: [ modifiers.iconSuccess ]
}, [])
```

**Theming**
By creating and passing a theme, the icon set can easily be changed:

![icon](https://cloud.githubusercontent.com/assets/814453/23800555/beeecb1c-05a4-11e7-9b35-51ced829c55d.gif)

**Comment by tomdye** [comment]
In summary, an icon widget does not provide a great deal of abstraction over simply creating an `<i>` with the appropriate class using `v`. But it does simplify the theming approach as the `Icon` can take it's own theme and thus avoid any potential classname clashes that may arise as a result of stacking `@theme` decorators.

Either way, in order to provide consistent theming throughout our widget suite we should ensure that we use a shared `icon.css` at the very least.

There may be further abstractions that I have not yet thought about.

**Comment by rishson** [comment]
@matt-gadd @agubler @smhigley @bitpshr ca we get agreement on if we should implement an `Icon` widget or not please (thoughts and opinions in here or #dojo2)?
I'd like to include either an `Icon` widget or a section in the `dojo/widgets` README on icon usage - for beta 1.

**Comment by tomdye** [comment]
The material design approach utilising ligatures is nice as well for screen readers and accessibility. So we should perhaps consider that too.

ie. `<i class='material-icon'>share</i>` would show a `share` icon.

I believe that @agubler has implemented / is implementing stacked theme decorators which means we can likely proceed with just an `icon.css` file instead of an icon widget.

**Comment by agubler** [comment]
All the theming benefits listed by @tomdye can be achieved by leveraging stackable themes (coming soon) with a common `icon.css` file, so we'd really need to list the "value add" abstractions that an Icon widget can deliver.

Something like:

```ts
import iconCss from './../common/styles/icon.css';
import css from './styles/MyStackedThemeWidget.css';

const MyStackedThemeWidgetBase = ThemeableMixin(WidgetBase);

@theme(iconCss)
@theme(css)
class MyStackedThemeWidget extends MyStackedThemeWidgetBase {

    render() {
         return v('i', { classes: this.classes(css.myClass, iconCss.commonIcon) });
    }
}
```

**Comment by smhigley** [comment]
I'm on board with the `icon.css` file over an icon widget. I tried out the icon widget, and ran into a few minor contortions to style it when used in another widget, and I think we could accomplish the same thing with just shared css.

I've looked at ligatures, but they aren't supported by something like 30% of US users, including browsers we support. The method for using it also isn't fully standardized yet. It would be nice in the future, but I don't think it's a good idea right now.

**Comment by smhigley** [comment]
There is one benefit I can see to having a widget -- better a11y and fallbacks. I don't think it's quite worth having the widget, though. We can do it right in all our widgets, and provide guidelines in the README for proper icon creation.

**Comment by agubler** [comment]
@smhigley Those were two of the value adds that @rishson mentioned and I'm happy if we feel that they (and other abstractions) make it worthwhile supporting an `Icon` widget - That's what we really need to decide.

**Comment by smhigley** [comment]
@agubler I'm still on the side of not having an `Icon` widget, mostly. The a11y is only a single attribute: `aria-hidden: true`, assuming the widget is only decorative. If it's not decorative, you can drop the `aria-hidden`, but should add some visually hidden text. That's it!

Bonus points if the visually hidden text becomes visible when the icon font doesn't load, but since we won't be handling those tests ourselves that should be a user concern anyway.

**Comment by tomdye** [comment]
@smhigley when i looked into it, i thought they were supported by all the browsers we're targeting, happy to be proved wrong

**Comment by smhigley** [comment]
@tomdye it's silly IE again, and Edge too :(

**Comment by smhigley** [comment]
There are also a number of other issues we'd have to iron out. Internationalization would be a pain (would we just have a different icon font for each language, or would we write a build task to map translations to the correct icon, resulting in a much larger font file?).

We'd also have to take icons out of pseudo-elements to take advantage of it, since screen readers don't reliably read css content (some do, some don't). That's not necessarily an issue, just a difference.

Ligatures started as SVG spec, which is why they still lack broad support outside of SVG. `text-rendering: optimizeLegibility` is really just a hack -- ligatures are a side effect of it, but they can be dependent on text size. Hopefully someday soon we'll have good support and be able to use them. I'd really like to as well 😃

**Comment by rishson** [comment]
It appears we have consensus that we should just ship `icons.css` rather than implement a widget.
I'm linking to dojo/widget-core#401, as that is also needed for a complete implementation.
This ticket now tracks the work needed to implement the `icons.css` css generations and documentation of the internal process to update that file when a new version of fontawesome comes out.
