### ISSUE TITLE
Input Chips widget

### ISSUE THREAD

**Issue by rorticus** [dojo/widgets#598]
Create an input chips widget modeled after the usages defined in the [material input chip usages](https://material.io/design/components/chips.html#usage).

**Comment by rorticus** [comment]
WIP https://github.com/rorticus/widgets/tree/issue-598

**Comment by smhigley** [comment]
Going to close this issue for now, until there are better specs for a chip widget. The material design guidelines are not suited for direct translation to a widget for the following reasons:

- The use cases include the following, each of which requires different base elements or semantic sugar: radios, checkboxes, simple buttons, toggle buttons, and popup buttons
- The expected pointer and keyboard interactivity for several of the use cases is wildly divergent, and does not fit well into a single widget

Chips in general seem to call for the ability to apply a uniform skin over a few different existing widgets rather than a single widget addition.
