### ISSUE TITLE
Proposal: CompositeWidget

### ISSUE THREAD

**Issue by rishson** [dojo/widgets#84]
**Enhancement** 

Proposal to follow

**Comment by matt-gadd** [comment]
## d, v and w

### Problem

At the moment, writing composite widgets is quite a pain. First of all there is no clear
lifecycle point to factory widgets, you have to manually manage the children on a state change
event, and you have to manually destroy those widgets. On top of this you then still need
to actually call render on them in the `getChildrenNodes` function in any scenario that involves wrapper `HyperScript`. This really is all quite ungainly to look at and is prone to errors and side effects.

### What we know

* We know that all children widgets in a composite widget, have derivative state
* We know at the point of rendering that the state exists

### Proposal

That we change the `getChildrenNodes` function to `getChildren` and we no longer return an array of `VNode`'s. We instead return an array of intemediary wrapper format(s) of `VWrapper` or `WWrapper`.

#### v
`v` - is an abstraction on top of `h`. The difference is, although it has the same argument signature of `h` it returns a `VWrapper` rather than a `VNode`. The `VWrapper` returns a `render` function with the `h` call inside (making it lazy). the `VWrapper` also contains an unprocessed array of `children` that were passed.

An example usage of `v` looks identical to current `h` usage:

```typescript
v('label', { innerHTML: 'Plain old HyperScript' });

```

This also will fix https://github.com/dojo/widgets/issues/43 by virtue. :)

#### w
`w` - provides a wrapper for widget factories. The `WWrapper` contains the `factory` and the `options` passed to it. Again the `factory` is not immediately executed.

An example usage of `w`:

```typescript
w(createCheckboxInput, {
	listeners: { change: () => toggle.do(state) },
	state: { classes: [ 'toggle' ], checked }
});
```

#### d
`d` - is the convenience api which delegates to either `v` or `w` based on the first argument passed. If the first param is of type `string`; `v` will be used, if the first param is a `factory`; `w` will be used. You can write either of the above examples with just `d`.

#### Rendering
Because we are now lazily calling `maquette`, we can process these intermediary `VWrapper` and `WWrappers` in the `render` function. During the `render` call we recurse through the returned children performing the following:

If the child is of type `WWrapper`:

+ If the factory is not in the `childrenCache` (`Map` of `factory`, `instance`) from a previous render
	+ Factory the widget with the provided `factory` and `options`
	+ Add it to the `childrenCache`
	+ `own` it
+ If the factory is in the children cache from a previous render
	+ Use the instance from the `childrenCache`
	+ Call `setState` with the provided `options.state`
+ Add the widget to a `currentChildrenCache`
+ Call `render`

If the child is of type `VWrapper`:

+ If the child has children, recurse again (the children can be of either `VWrapper` or `WWrapper`)
	+ Prune any `null` entries
	+ Set the resulting children on this `VWrapper`
+ Call `render`

Once recursed, we now have our final array of `VNodes` to render.

#### Destroying
We can now also automatically remove child widgets that are not needed in our `pruneChildren` function. Here we:

+ Compare the `childrenCache` from the previous render, with the `currentChildrenCache` from the current render, if any instances exist in the `childrenCache`, that do not in the `currentChildrenCache`, then we remove it from the `childrenCache`, and call `destroy` on the widget. The `currentChildrenCache` is completely reset on every render.

### Result

With the above in place, we now have one place to deal with both `HyperScript` and `widgets`, we no longer have to worry about binding to any state events, nor do we have to worry about the factorying or destroying of widgets. An example of what the `getChildren` (or equivalent) function would look like for `createTodoItem` (compared to the original [here](https://github.com/dojo/examples/blob/master/todo-mvc/src/widgets/createTodoItem.ts)):

```typescript
getChildren(this: TodoItem): DWrapper[] {
	const state = this.state;
	const checked = state.completed;
	const label = state.label;
	const focused = state.editing;
	return [
		d('div.view', [
			d(createCheckboxInput, {
				listeners: { change: () => todoToggleComplete.do(state) },
				state: { classes: [ 'toggle' ], checked }
			}),
			d(createLabel, {
				listeners: { dblclick: () => todoEdit.do(state) },
				state: { label }
			}),
			d(createButton, {
				listeners: { click: () => todoRemove.do(state) },
				state: { classes: [ 'destroy' ] }
			})
		]),
		d(createFocusableTextInput, {
			listeners: {
				blur: (evt: Event) => todoSave.do({ state, evt }),
				keyup: (evt: Event) => todoEditInput.do({ state, evt })
			},
			state: { value: label, focused, classes: [ 'edit' ] }
		})
	];
},

```

Making things more exciting we could conditionally include/exclude a widget (it will be automatically factoried and destroyed) in the above like so :

```typescript
checked ? d(createLabel, {
	key: 'my-other-label',
	state: { label: `${label} I will appear when checked!` }
}) : null
```

### Notes

#### Dealing with multiple instances of the same factory. 

Because the children are cached by factory, if you use the same factory more than once then we cannot determine which to `setState` on, or which to `destroy` if one is removed during `getChildren`. The solution here would be for the author to provide a `key` (or potentially `id` given its common for widgets already) like `maquette` or `react`, this would be then used in the `childrenCache` rather than the factory to avoid conflicts.

#### Dealing with option changes other than state.

If `options` other than `state` change between renders, we are likely to want to destroy and re-factory the widget.

#### TSX

The combined `d` api would provide the capability we need to support TSX potentially in the future.


#### POC in todo-mvc
Code for `createTodoItem.ts`: [here](https://gist.github.com/matt-gadd/1836de40c86bc360b398119d9ce8103f)
